from contextlib import AbstractContextManager
from typing import Protocol


class ProgressReporterPort(Protocol):
    def advance(self, amount: int = 1) -> None: ...

    def set_total(self, total: int) -> None: ...

    def set_description(self, description: str) -> None: ...

    def set_status(self, status: str) -> None: ...

    def set_secondary_status(self, status: str) -> None: ...

    def set_loading_progress(self, completed: int, total: int, stage: str) -> None: ...

    def set_processing_status(self, status: str) -> None: ...

    def set_failed_status(self, status: str) -> None: ...

    def set_completed(self, completed: int) -> None: ...

    def stop(self) -> None: ...


class ProgressReporterFactoryPort(Protocol):
    def create(
        self,
        total: int,
        description: str,
        *,
        download_mode: bool = False,
        extract_mode: bool = False,
    ) -> AbstractContextManager[ProgressReporterPort]: ...
