from __future__ import annotations

import re
import shutil
import subprocess
from collections.abc import Callable
from pathlib import Path
from zipfile import ZipFile

from ba_downloader.domain.models.runtime import RuntimeContext
from ba_downloader.domain.ports.extract import Il2CppDumpBackendPort
from ba_downloader.domain.ports.http import HttpClientPort
from ba_downloader.domain.ports.logging import LoggerPort
from ba_downloader.domain.ports.region import Region
from ba_downloader.infrastructure.tools.il2cpp_dumper import IL2CppDumper
from ba_downloader.infrastructure.tools.runtime_probe import (
    get_installed_dotnet_sdk_major_versions,
)

CPP2IL_COMMIT = "10db0e546fab83ec67380046f1088b62c7b38ea5"
CPP2IL_ARCHIVE_URL = (
    f"https://github.com/SamboyCoding/Cpp2IL/archive/{CPP2IL_COMMIT}.zip"
)
CPP2IL_PROJECT = Path("Cpp2IL") / "Cpp2IL.csproj"
LIBCPP2IL_PROJECT = Path("LibCpp2IL") / "LibCpp2IL.csproj"
EXPORTER_PROJECT_NAME = "dumpcs_exporter"
UNITY_VERSION_PATTERN = re.compile(r"(20\d{2}\.\d+\.\d+[a-z]\d+)", re.IGNORECASE)

EXPORTER_CSPROJ_TEMPLATE = """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="{libcpp2il_reference}" />
  </ItemGroup>
</Project>
"""

EXPORTER_PROGRAM_CS = """using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using AssetRipper.Primitives;
using LibCpp2IL;
using LibCpp2IL.BinaryStructures;
using LibCpp2IL.Metadata;

internal static class Program
{
    private static int Main(string[] args)
    {
        try
        {
            var options = ParseArgs(args);
            if (options is null)
            {
                PrintUsage();
                return 1;
            }

            RequireFile(options.BinaryPath);
            RequireFile(options.MetadataPath);

            var unityVersion = string.IsNullOrWhiteSpace(options.UnityVersion)
                ? throw new InvalidOperationException("Missing unity version. Please pass --unity-version.")
                : UnityVersion.Parse(options.UnityVersion);

            if (!LibCpp2IlMain.LoadFromFile(options.BinaryPath, options.MetadataPath, unityVersion))
                throw new InvalidOperationException("Failed to load IL2CPP binary and metadata.");

            var metadata = LibCpp2IlMain.TheMetadata ?? throw new InvalidOperationException("Metadata not initialized.");
            var outputPath = Path.GetFullPath(options.OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

            using var writer = new StreamWriter(outputPath, false, new UTF8Encoding(false));
            WriteHeader(writer, options, unityVersion, metadata);

            for (var imageIndex = 0; imageIndex < metadata.imageDefinitions.Length; imageIndex++)
            {
                var image = metadata.imageDefinitions[imageIndex];
                var types = image.Types ?? [];

                writer.WriteLine();
                writer.WriteLine($"// Image {imageIndex}: {image.Name}");
                writer.WriteLine($"// Token: 0x{image.token:X8}");
                writer.WriteLine();

                foreach (var type in types.Where(t => t.DeclaringType is null))
                    WriteType(writer, type, 0);
            }

            Console.WriteLine($"dump.cs exported to {outputPath}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
            return 1;
        }
    }

    private static void WriteHeader(
        StreamWriter writer,
        Options options,
        UnityVersion unityVersion,
        Il2CppMetadata metadata)
    {
        writer.WriteLine("// dump.cs generated by ba-downloader dumpcs_exporter");
        writer.WriteLine($"// Binary: {options.BinaryPath}");
        writer.WriteLine($"// Metadata: {options.MetadataPath}");
        writer.WriteLine($"// UnityVersion: {unityVersion}");
        writer.WriteLine($"// MetadataVersion: {metadata.MetadataVersion}");
        writer.WriteLine($"// TypeDefinitions: {metadata.TypeDefinitionCount}");
        writer.WriteLine($"// MethodDefinitions: {metadata.MethodDefinitionCount}");
    }

    private static void WriteType(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var indentation = new string(' ', indent * 4);
        var namespaceName = string.IsNullOrEmpty(type.Namespace) ? "-" : type.Namespace;

        writer.WriteLine($"{indentation}// Namespace: {namespaceName}");
        writer.WriteLine($"{indentation}{BuildTypeDeclaration(type)} // TypeDefIndex: {type.TypeIndex.Value} Token: 0x{type.Token:X8}");
        writer.WriteLine($"{indentation}{{");

        WriteFields(writer, type, indent + 1);
        WriteProperties(writer, type, indent + 1);
        WriteMethods(writer, type, indent + 1);

        var nestedTypes = type.NestedTypes ?? [];
        if (nestedTypes.Length > 0)
        {
            writer.WriteLine();
            writer.WriteLine($"{new string(' ', (indent + 1) * 4)}// Nested Types");
            foreach (var nestedType in nestedTypes)
            {
                writer.WriteLine();
                WriteType(writer, nestedType, indent + 1);
            }
        }

        writer.WriteLine($"{indentation}}}");
        writer.WriteLine();
    }

    private static void WriteFields(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var fields = type.FieldInfos ?? [];
        if (fields.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine($"{indentation}// Fields");
        foreach (var field in fields)
        {
            var offset = field.FieldOffset >= 0 ? $"0x{field.FieldOffset:X}" : "static";
            writer.WriteLine(
                $"{indentation}{BuildFieldDeclaration(field.Field, field.Attributes)}; // {offset} Token: 0x{field.Field.token:X8}");
        }
    }

    private static void WriteProperties(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var properties = type.Properties ?? [];
        if (properties.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine();
        writer.WriteLine($"{indentation}// Properties");
        foreach (var property in properties)
        {
            var getter = property.Getter is not null ? "get; " : string.Empty;
            var setter = property.Setter is not null ? "set; " : string.Empty;
            var propertyType = CleanTypeName(property.PropertyType?.ToString() ?? "void");
            writer.WriteLine(
                $"{indentation}{BuildPropertyAccess(property)} {propertyType} {SanitizeIdentifier(property.Name ?? "property")} {{ {getter}{setter}}} // Token: 0x{property.token:X8}");
        }
    }

    private static void WriteMethods(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var methods = type.Methods ?? [];
        if (methods.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine();
        writer.WriteLine($"{indentation}// Methods");
        foreach (var method in methods)
        {
            writer.WriteLine(
                $"{indentation}// RVA: 0x{method.Rva:X} Offset: 0x{method.MethodOffsetInFile:X} VA: 0x{method.MethodPointer:X} Slot: {method.slot} Token: 0x{method.token:X8}");
            writer.WriteLine($"{indentation}{BuildMethodDeclaration(method)} {{ }}");
        }
    }

    private static string BuildTypeDeclaration(Il2CppTypeDefinition type)
    {
        var parts = new List<string> { BuildTypeAccess(type) };
        if (type.IsInterface)
        {
            parts.Add("interface");
        }
        else if (type.IsEnumType)
        {
            parts.Add("enum");
        }
        else if (type.IsValueType)
        {
            parts.Add("struct");
        }
        else
        {
            if (type.Attributes.HasFlag(TypeAttributes.Abstract) && type.Attributes.HasFlag(TypeAttributes.Sealed))
                parts.Add("static");
            else
            {
                if (type.Attributes.HasFlag(TypeAttributes.Abstract))
                    parts.Add("abstract");
                if (type.Attributes.HasFlag(TypeAttributes.Sealed))
                    parts.Add("sealed");
            }

            parts.Add("class");
        }

        parts.Add(BuildTypeName(type));

        var inheritance = new List<string>();
        if (!type.IsInterface && !type.IsEnumType && !type.IsValueType)
        {
            var baseTypeName = CleanTypeName(type.BaseType?.ToString() ?? string.Empty);
            if (!string.IsNullOrEmpty(baseTypeName) && baseTypeName != "System.Object" && baseTypeName != "void")
                inheritance.Add(baseTypeName);
        }

        var interfaces = type.Interfaces ?? [];
        inheritance.AddRange(interfaces.Select(i => CleanTypeName(i.ToString())));
        if (inheritance.Count > 0)
            parts.Add(": " + string.Join(", ", inheritance.Distinct()));

        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildFieldDeclaration(Il2CppFieldDefinition field, FieldAttributes attributes)
    {
        var parts = new List<string> { BuildFieldAccess(attributes) };
        if (attributes.HasFlag(FieldAttributes.Static))
            parts.Add("static");
        if (attributes.HasFlag(FieldAttributes.InitOnly))
            parts.Add("readonly");
        if (attributes.HasFlag(FieldAttributes.Literal))
            parts.Add("const");
        parts.Add(CleanTypeName(field.FieldType?.ToString() ?? "void"));
        parts.Add(SanitizeIdentifier(field.Name ?? "field"));
        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildMethodDeclaration(Il2CppMethodDefinition method)
    {
        var parts = new List<string> { BuildMethodAccess(method.Attributes) };
        if (method.IsStatic)
            parts.Add("static");
        if (method.Attributes.HasFlag(MethodAttributes.Abstract))
            parts.Add("abstract");
        else if (method.Attributes.HasFlag(MethodAttributes.Virtual))
            parts.Add("virtual");

        parts.Add(CleanTypeName(method.ReturnType?.ToString() ?? "void"));
        parts.Add(BuildMethodName(method) + BuildParameterList(method));
        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildMethodName(Il2CppMethodDefinition method)
    {
        var methodName = SanitizeIdentifier(method.Name ?? "Method");
        var genericParameters = method.GenericContainer?.GenericParameters.Select(p => SanitizeIdentifier(p.Name ?? $"T{p.genericParameterIndexInOwner}")).ToArray() ?? [];
        if (genericParameters.Length == 0)
            return methodName;
        return $"{methodName}<{string.Join(", ", genericParameters)}>";
    }

    private static string BuildParameterList(Il2CppMethodDefinition method)
    {
        var parameters = method.Parameters ?? [];
        var rendered = parameters.Select(p =>
        {
            var modifier = p.Attributes.HasFlag(ParameterAttributes.Out) ? "out " :
                p.RawType?.Type == Il2CppTypeEnum.IL2CPP_TYPE_BYREF ? "ref " : string.Empty;
            return $"{modifier}{CleanTypeName(p.Type.ToString())} {SanitizeIdentifier(p.ParameterName ?? $"param{p.ParameterIndex}")}";
        });

        return "(" + string.Join(", ", rendered) + ")";
    }

    private static string BuildTypeName(Il2CppTypeDefinition type)
    {
        var name = SanitizeIdentifier(type.Name ?? "Type");
        var genericParameters = type.GenericContainer?.GenericParameters.Select(p => SanitizeIdentifier(p.Name ?? $"T{p.genericParameterIndexInOwner}")).ToArray() ?? [];
        if (genericParameters.Length == 0)
            return name;
        return $"{name}<{string.Join(", ", genericParameters)}>";
    }

    private static string BuildTypeAccess(Il2CppTypeDefinition type)
    {
        var visibility = type.Attributes & TypeAttributes.VisibilityMask;
        return visibility switch
        {
            TypeAttributes.Public or TypeAttributes.NestedPublic => "public",
            TypeAttributes.NestedFamily => "protected",
            TypeAttributes.NestedFamORAssem => "protected internal",
            TypeAttributes.NotPublic => "internal",
            _ => "private",
        };
    }

    private static string BuildFieldAccess(FieldAttributes attributes)
    {
        var access = attributes & FieldAttributes.FieldAccessMask;
        return access switch
        {
            FieldAttributes.Public => "public",
            FieldAttributes.Family => "protected",
            FieldAttributes.FamORAssem => "protected internal",
            FieldAttributes.Assembly => "internal",
            _ => "private",
        };
    }

    private static string BuildMethodAccess(MethodAttributes attributes)
    {
        var access = attributes & MethodAttributes.MemberAccessMask;
        return access switch
        {
            MethodAttributes.Public => "public",
            MethodAttributes.Family => "protected",
            MethodAttributes.FamORAssem => "protected internal",
            MethodAttributes.Assembly => "internal",
            _ => "private",
        };
    }

    private static string BuildPropertyAccess(Il2CppPropertyDefinition property)
    {
        var accessor = property.Getter ?? property.Setter;
        return accessor is null ? "public" : BuildMethodAccess(accessor.Attributes);
    }

    private static string CleanTypeName(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "void";
        return Regex.Replace(raw, @"`\\d+", string.Empty).Replace('+', '.');
    }

    private static string SanitizeIdentifier(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "_";
        return Regex.Replace(raw, @"`\\d+", string.Empty);
    }

    private static void RequireFile(string path)
    {
        if (!File.Exists(path))
            throw new FileNotFoundException("File not found: " + path);
    }

    private static Options? ParseArgs(string[] args)
    {
        string? binaryPath = null;
        string? metadataPath = null;
        string? outputPath = null;
        string? unityVersion = null;

        foreach (var arg in args)
        {
            if (arg.StartsWith("--binary-path=", StringComparison.OrdinalIgnoreCase))
                binaryPath = arg["--binary-path=".Length..].Trim('"');
            else if (arg.StartsWith("--metadata-path=", StringComparison.OrdinalIgnoreCase))
                metadataPath = arg["--metadata-path=".Length..].Trim('"');
            else if (arg.StartsWith("--output=", StringComparison.OrdinalIgnoreCase))
                outputPath = arg["--output=".Length..].Trim('"');
            else if (arg.StartsWith("--unity-version=", StringComparison.OrdinalIgnoreCase))
                unityVersion = arg["--unity-version=".Length..].Trim('"');
        }

        if (string.IsNullOrWhiteSpace(binaryPath) || string.IsNullOrWhiteSpace(metadataPath) || string.IsNullOrWhiteSpace(outputPath))
            return null;

        return new Options(binaryPath, metadataPath, outputPath, unityVersion ?? string.Empty);
    }

    private static void PrintUsage()
    {
        Console.WriteLine("Usage:");
        Console.WriteLine("  dotnet run --project dumpcs_exporter -- --binary-path=<path> --metadata-path=<path> --unity-version=<version> --output=<path>");
    }

    private sealed record Options(
        string BinaryPath,
        string MetadataPath,
        string OutputPath,
        string UnityVersion);
}
"""


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _find_first_match(base_dir: Path, file_names: tuple[str, ...]) -> Path | None:
    for file_name in file_names:
        matches = list(base_dir.rglob(file_name))
        if matches:
            return matches[0]
    return None


class LegacyIl2CppDumperBackend(Il2CppDumpBackendPort):
    IL2CPP_NAME = "libil2cpp.so"
    METADATA_NAME = "global-metadata.dat"

    def __init__(self, http_client: HttpClientPort, logger: LoggerPort) -> None:
        self.http_client = http_client
        self.logger = logger

    def dump(self, context: RuntimeContext, output_dir: str) -> None:
        dumper = IL2CppDumper()
        self.logger.info("Downloading il2cpp-dumper...")
        dumper.get_il2cpp_dumper(self.http_client, context.temp_dir)

        base_dir = Path(context.temp_dir)
        il2cpp_path = _find_first_match(base_dir, (self.IL2CPP_NAME,))
        metadata_path = _find_first_match(base_dir, (self.METADATA_NAME,))
        if not (il2cpp_path and metadata_path):
            raise FileNotFoundError(
                "Cannot find il2cpp binary file or global-metadata file. Make sure they exist.",
            )

        self.logger.info("Trying to dump il2cpp...")
        dumper.dump_il2cpp(
            output_dir,
            str(il2cpp_path.resolve()),
            str(metadata_path.resolve()),
            context.max_retries,
        )
        self.logger.info("Dumped il2cpp binary file successfully.")


class Cpp2ILSourceResolver:
    def __init__(
        self,
        http_client: HttpClientPort,
        logger: LoggerPort,
        commit: str = CPP2IL_COMMIT,
        archive_url: str = CPP2IL_ARCHIVE_URL,
    ) -> None:
        self.http_client = http_client
        self.logger = logger
        self.commit = commit
        self.archive_url = archive_url

    def resolve(self, context: RuntimeContext) -> Path:
        submodule_root = _repo_root() / "third_party" / "Cpp2IL"
        if self._is_valid_cpp2il_root(submodule_root):
            return submodule_root

        cache_root = self._cache_root(context)
        if self._is_valid_cpp2il_root(cache_root):
            return cache_root

        self.logger.warn("Cpp2IL source is missing. Downloading fallback source package...")
        self._download_to_cache(cache_root)
        if self._is_valid_cpp2il_root(cache_root):
            return cache_root
        raise FileNotFoundError("Unable to resolve a valid Cpp2IL source tree.")

    def _cache_root(self, context: RuntimeContext) -> Path:
        return (
            Path(context.work_dir)
            / ".ba-downloader"
            / "tools"
            / f"Cpp2IL-{self.commit[:12]}"
        )

    @staticmethod
    def _is_valid_cpp2il_root(root: Path) -> bool:
        return (root / CPP2IL_PROJECT).exists() and (root / LIBCPP2IL_PROJECT).exists()

    def _download_to_cache(self, cache_root: Path) -> None:
        cache_root.parent.mkdir(parents=True, exist_ok=True)
        archive_path = cache_root.parent / f"cpp2il-{self.commit}.zip"
        extract_dir = cache_root.parent / f"cpp2il-{self.commit}-extract"

        if extract_dir.exists():
            shutil.rmtree(extract_dir)
        if archive_path.exists():
            archive_path.unlink()

        self.http_client.download_to_file(self.archive_url, str(archive_path))
        with ZipFile(archive_path, "r") as archive:
            archive.extractall(extract_dir)

        source_root = next(
            (
                path
                for path in extract_dir.iterdir()
                if path.is_dir() and self._is_valid_cpp2il_root(path)
            ),
            None,
        )
        if source_root is None:
            raise FileNotFoundError(
                "Downloaded Cpp2IL archive does not contain expected project files.",
            )

        if cache_root.exists():
            shutil.rmtree(cache_root)
        shutil.move(str(source_root), str(cache_root))

        if archive_path.exists():
            archive_path.unlink()
        if extract_dir.exists():
            shutil.rmtree(extract_dir)


class Cpp2IlDumpCsBackend(Il2CppDumpBackendPort):
    BINARY_CANDIDATES = ("GameAssembly.dll", "libil2cpp.so")
    METADATA_NAME = "global-metadata.dat"
    UNITY_VERSION_ENV = "BA_CPP2IL_UNITY_VERSION"
    GLOBAL_GAME_MANAGERS = "globalgamemanagers"

    def __init__(
        self,
        http_client: HttpClientPort,
        logger: LoggerPort,
        source_resolver: Cpp2ILSourceResolver | None = None,
    ) -> None:
        self.http_client = http_client
        self.logger = logger
        self.source_resolver = source_resolver or Cpp2ILSourceResolver(http_client, logger)

    def dump(self, context: RuntimeContext, output_dir: str) -> None:
        base_dir = Path(context.temp_dir)
        binary_path = _find_first_match(base_dir, self.BINARY_CANDIDATES)
        metadata_path = _find_first_match(base_dir, (self.METADATA_NAME,))
        if not binary_path or not metadata_path:
            raise FileNotFoundError(
                "Cannot find binary file or global-metadata file for Cpp2IL backend.",
            )

        unity_version = self._resolve_unity_version(context, base_dir)
        if not unity_version:
            raise LookupError(
                "Cannot determine Unity version for Cpp2IL backend. "
                "Set BA_CPP2IL_UNITY_VERSION or ensure globalgamemanagers exists in temp files.",
            )

        cpp2il_root = self.source_resolver.resolve(context)
        exporter_project = self._ensure_exporter_project(context, cpp2il_root)
        dump_cs_path = Path(output_dir) / "dump.cs"
        dump_cs_path.parent.mkdir(parents=True, exist_ok=True)

        frameworks = self._resolve_framework_order()
        errors: list[str] = []
        for index, framework in enumerate(frameworks):
            if index > 0:
                self.logger.warn(
                    f"Retrying Cpp2IL exporter with framework {framework}.",
                )
            try:
                subprocess.run(
                    [
                        "dotnet",
                        "run",
                        "--project",
                        str(exporter_project),
                        "--framework",
                        framework,
                        "--",
                        f"--binary-path={binary_path.resolve()}",
                        f"--metadata-path={metadata_path.resolve()}",
                        f"--unity-version={unity_version}",
                        f"--output={dump_cs_path.resolve()}",
                    ],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    check=True,
                    text=True,
                    encoding="utf8",
                )
                self.logger.info("Dumped il2cpp binary file successfully.")
                return
            except subprocess.CalledProcessError as exc:
                errors.append(exc.stderr.strip() or str(exc))

        raise RuntimeError(
            "Failed to dump il2cpp with Cpp2IL backend: " + " | ".join(errors),
        )

    def _resolve_unity_version(self, context: RuntimeContext, temp_dir: Path) -> str:
        import os

        if env_value := os.getenv(self.UNITY_VERSION_ENV, "").strip():
            return env_value

        managers = list(temp_dir.rglob(self.GLOBAL_GAME_MANAGERS))
        for manager_path in managers:
            try:
                raw = manager_path.read_bytes().decode("latin-1", errors="ignore")
            except Exception:
                continue
            if match := UNITY_VERSION_PATTERN.search(raw):
                return match.group(1)

        return ""

    @staticmethod
    def _resolve_framework_order() -> tuple[str, ...]:
        installed = get_installed_dotnet_sdk_major_versions()
        frameworks: list[str] = []
        if 9 in installed:
            frameworks.append("net9.0")
        if 8 in installed:
            frameworks.append("net8.0")
        if not frameworks:
            raise FileNotFoundError(
                "Error: .NET 9 or .NET 8 SDK is required for the Cpp2IL dumper backend.",
            )
        return tuple(frameworks)

    @staticmethod
    def _ensure_exporter_project(context: RuntimeContext, cpp2il_root: Path) -> Path:
        export_root = Path(context.work_dir) / ".ba-downloader" / "tools" / EXPORTER_PROJECT_NAME
        export_root.mkdir(parents=True, exist_ok=True)

        project_path = export_root / f"{EXPORTER_PROJECT_NAME}.csproj"
        program_path = export_root / "Program.cs"
        libcpp2il_reference = (cpp2il_root / LIBCPP2IL_PROJECT).resolve().as_posix()

        project_path.write_text(
            EXPORTER_CSPROJ_TEMPLATE.format(libcpp2il_reference=libcpp2il_reference),
            encoding="utf8",
        )
        program_path.write_text(EXPORTER_PROGRAM_CS, encoding="utf8")
        return project_path


BackendFactory = Callable[[HttpClientPort, LoggerPort], Il2CppDumpBackendPort]


class DumperBackendRegistry:
    def __init__(self) -> None:
        self._factories: dict[Region, BackendFactory] = {}

    def register(self, region: Region, factory: BackendFactory) -> None:
        self._factories[region] = factory

    def resolve(self, region: Region) -> BackendFactory:
        if region not in self._factories:
            raise KeyError(f"Region '{region}' is not registered.")
        return self._factories[region]


def build_default_dumper_backend_registry() -> DumperBackendRegistry:
    registry = DumperBackendRegistry()
    registry.register("cn", lambda http_client, logger: LegacyIl2CppDumperBackend(http_client, logger))
    registry.register("gl", lambda http_client, logger: LegacyIl2CppDumperBackend(http_client, logger))
    registry.register("jp", lambda http_client, logger: Cpp2IlDumpCsBackend(http_client, logger))
    return registry


DEFAULT_DUMPER_BACKEND_REGISTRY = build_default_dumper_backend_registry()
