using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using AssetRipper.Primitives;
using LibCpp2IL;
using LibCpp2IL.BinaryStructures;
using LibCpp2IL.Metadata;

internal static class Program
{
    private static int Main(string[] args)
    {
        try
        {
            var options = ParseArgs(args);
            if (options is null)
            {
                PrintUsage();
                return 1;
            }

            RequireFile(options.BinaryPath);
            RequireFile(options.MetadataPath);

            var unityVersion = string.IsNullOrWhiteSpace(options.UnityVersion)
                ? throw new InvalidOperationException("Missing unity version. Please pass --unity-version.")
                : UnityVersion.Parse(options.UnityVersion);

            if (options.EnableCnMetadataRecoveryShim)
                RegisterCnMetadataRecoveryShim();

            if (!LibCpp2IlMain.LoadFromFile(options.BinaryPath, options.MetadataPath, unityVersion))
                throw new InvalidOperationException("Failed to load IL2CPP binary and metadata.");

            var metadata = LibCpp2IlMain.TheMetadata ?? throw new InvalidOperationException("Metadata not initialized.");
            var outputPath = Path.GetFullPath(options.OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

            using var writer = new StreamWriter(outputPath, false, new UTF8Encoding(false));
            WriteHeader(writer, options, unityVersion, metadata);

            for (var imageIndex = 0; imageIndex < metadata.imageDefinitions.Length; imageIndex++)
            {
                var image = metadata.imageDefinitions[imageIndex];
                var types = image.Types ?? [];

                writer.WriteLine();
                writer.WriteLine($"// Image {imageIndex}: {image.Name}");
                writer.WriteLine($"// Token: 0x{image.token:X8}");
                writer.WriteLine();

                foreach (var type in types.Where(t => t.DeclaringType is null))
                    WriteType(writer, type, 0);
            }

            if (!string.IsNullOrWhiteSpace(options.FormatterOutputPath))
            {
                WriteMemoryPackFormatterSidecar(metadata, options.FormatterOutputPath);
                WriteMemoryPackUnionAttributeSidecar(
                    metadata,
                    Path.Combine(
                        Path.GetDirectoryName(Path.GetFullPath(options.FormatterOutputPath))!,
                        "memorypack_union_attrs.json"));
            }

            Console.WriteLine($"dump.cs exported to {outputPath}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
            return 1;
        }
    }

    private static void RegisterCnMetadataRecoveryShim()
    {
        var shimType = typeof(Program).Assembly.GetType("CnMetadataRecoveryInputShim")
            ?? throw new InvalidOperationException(
                "CN metadata recovery shim source was not included in the exporter project.");
        var register = shimType.GetMethod(
            "Register",
            BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
            ?? throw new InvalidOperationException(
                "CN metadata recovery shim does not expose a Register method.");
        register.Invoke(null, null);
    }

    private static void WriteHeader(
        StreamWriter writer,
        Options options,
        UnityVersion unityVersion,
        Il2CppMetadata metadata)
    {
        writer.WriteLine("// dump.cs generated by ba-downloader dumpcs_exporter");
        writer.WriteLine($"// Binary: {options.BinaryPath}");
        writer.WriteLine($"// Metadata: {options.MetadataPath}");
        writer.WriteLine($"// UnityVersion: {unityVersion}");
        writer.WriteLine($"// MetadataVersion: {metadata.MetadataVersion}");
        writer.WriteLine($"// TypeDefinitions: {metadata.TypeDefinitionCount}");
        writer.WriteLine($"// MethodDefinitions: {metadata.MethodDefinitionCount}");
    }

    private static void WriteType(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var indentation = new string(' ', indent * 4);
        var namespaceName = string.IsNullOrEmpty(type.Namespace) ? "-" : type.Namespace;

        writer.WriteLine($"{indentation}// Namespace: {namespaceName}");
        writer.WriteLine($"{indentation}{BuildTypeDeclaration(type)} // TypeDefIndex: {type.TypeIndex.Value} Token: 0x{type.Token:X8}");
        writer.WriteLine($"{indentation}{{");

        WriteFields(writer, type, indent + 1);
        WriteProperties(writer, type, indent + 1);
        WriteMethods(writer, type, indent + 1);

        var nestedTypes = type.NestedTypes ?? [];
        if (nestedTypes.Length > 0)
        {
            writer.WriteLine();
            writer.WriteLine($"{new string(' ', (indent + 1) * 4)}// Nested Types");
            foreach (var nestedType in nestedTypes)
            {
                writer.WriteLine();
                WriteType(writer, nestedType, indent + 1);
            }
        }

        writer.WriteLine($"{indentation}}}");
        writer.WriteLine();
    }

    private static void WriteFields(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var fields = type.FieldInfos ?? [];
        if (fields.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine($"{indentation}// Fields");
        foreach (var field in fields)
        {
            var offset = field.FieldOffset >= 0 ? $"0x{field.FieldOffset:X}" : "static";
            writer.WriteLine(
                $"{indentation}{BuildFieldDeclaration(field.Field, field.Attributes)}; // {offset} Token: 0x{field.Field.token:X8}");
        }
    }

    private static void WriteProperties(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var properties = type.Properties ?? [];
        if (properties.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine();
        writer.WriteLine($"{indentation}// Properties");
        foreach (var property in properties)
        {
            var getter = property.Getter is not null ? "get; " : string.Empty;
            var setter = property.Setter is not null ? "set; " : string.Empty;
            var propertyType = CleanTypeName(property.PropertyType?.ToString() ?? "void");
            writer.WriteLine(
                $"{indentation}{BuildPropertyAccess(property)} {propertyType} {SanitizeIdentifier(property.Name ?? "property")} {{ {getter}{setter}}} // Token: 0x{property.token:X8}");
        }
    }

    private static void WriteMethods(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var methods = type.Methods ?? [];
        if (methods.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine();
        writer.WriteLine($"{indentation}// Methods");
        foreach (var method in methods)
        {
            writer.WriteLine(
                $"{indentation}// RVA: 0x{method.Rva:X} Offset: 0x{method.MethodOffsetInFile:X} VA: 0x{method.MethodPointer:X} Slot: {method.slot} Token: 0x{method.token:X8}");
            writer.WriteLine($"{indentation}{BuildMethodDeclaration(method)} {{ }}");
        }
    }

    private static string BuildTypeDeclaration(Il2CppTypeDefinition type)
    {
        var parts = new List<string> { BuildTypeAccess(type) };
        if (type.IsInterface)
        {
            parts.Add("interface");
        }
        else if (type.IsEnumType)
        {
            parts.Add("enum");
        }
        else if (type.IsValueType)
        {
            parts.Add("struct");
        }
        else
        {
            if (type.Attributes.HasFlag(TypeAttributes.Abstract) && type.Attributes.HasFlag(TypeAttributes.Sealed))
                parts.Add("static");
            else
            {
                if (type.Attributes.HasFlag(TypeAttributes.Abstract))
                    parts.Add("abstract");
                if (type.Attributes.HasFlag(TypeAttributes.Sealed))
                    parts.Add("sealed");
            }

            parts.Add("class");
        }

        parts.Add(BuildTypeName(type));

        var inheritance = new List<string>();
        if (!type.IsInterface && !type.IsEnumType && !type.IsValueType)
        {
            var baseTypeName = CleanTypeName(type.BaseType?.ToString() ?? string.Empty);
            if (!string.IsNullOrEmpty(baseTypeName) && baseTypeName != "System.Object" && baseTypeName != "void")
                inheritance.Add(baseTypeName);
        }

        var interfaces = type.Interfaces ?? [];
        inheritance.AddRange(interfaces.Select(i => CleanTypeName(i.ToString())));
        if (inheritance.Count > 0)
            parts.Add(": " + string.Join(", ", inheritance.Distinct()));

        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildFieldDeclaration(Il2CppFieldDefinition field, FieldAttributes attributes)
    {
        var parts = new List<string> { BuildFieldAccess(attributes) };
        if (attributes.HasFlag(FieldAttributes.Static))
            parts.Add("static");
        if (attributes.HasFlag(FieldAttributes.InitOnly))
            parts.Add("readonly");
        if (attributes.HasFlag(FieldAttributes.Literal))
            parts.Add("const");
        parts.Add(CleanTypeName(field.FieldType?.ToString() ?? "void"));
        parts.Add(SanitizeIdentifier(field.Name ?? "field"));
        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildMethodDeclaration(Il2CppMethodDefinition method)
    {
        var parts = new List<string> { BuildMethodAccess(method.Attributes) };
        if (method.IsStatic)
            parts.Add("static");
        if (method.Attributes.HasFlag(MethodAttributes.Abstract))
            parts.Add("abstract");
        else if (method.Attributes.HasFlag(MethodAttributes.Virtual))
            parts.Add("virtual");

        parts.Add(CleanTypeName(method.ReturnType?.ToString() ?? "void"));
        parts.Add(BuildMethodName(method) + BuildParameterList(method));
        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static void WriteMemoryPackFormatterSidecar(
        Il2CppMetadata metadata,
        string formatterOutputPath)
    {
        var formatters = new List<Dictionary<string, object?>>();
        foreach (var type in EnumerateTypes(metadata))
        {
            var baseTypeName = CleanTypeName(type.BaseType?.ToString() ?? string.Empty);
            var targetType = ExtractGenericArgument(
                baseTypeName,
                "MemoryPack.MemoryPackFormatter");
            if (string.IsNullOrWhiteSpace(targetType))
                continue;

            var deserializeMethod = (type.Methods ?? [])
                .FirstOrDefault(method => method.Name == "Deserialize");
            formatters.Add(new Dictionary<string, object?>
            {
                ["target_type"] = targetType,
                ["kind"] = "unresolved",
                ["formatter_type"] = BuildFullTypeName(type),
                ["formatter_token"] = $"0x{type.Token:X8}",
                ["method_token"] = deserializeMethod is null ? "" : $"0x{deserializeMethod.token:X8}",
                ["method_rva"] = deserializeMethod is null ? "" : $"0x{deserializeMethod.Rva:X}",
                ["members"] = Array.Empty<object>(),
                ["union_tags"] = new Dictionary<string, string>(),
                ["reason"] = "Formatter method body analysis is not implemented by dumpcs_exporter.",
            });
        }

        var outputPath = Path.GetFullPath(formatterOutputPath);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        var options = new JsonSerializerOptions { WriteIndented = true };
        File.WriteAllText(
            outputPath,
            JsonSerializer.Serialize(new { version = 0, formatters }, options),
            new UTF8Encoding(false));
    }

    private static void WriteMemoryPackUnionAttributeSidecar(
        Il2CppMetadata metadata,
        string unionOutputPath)
    {
        var targets = new List<Dictionary<string, object?>>();
        if (metadata.MetadataVersion >= 29 && metadata.AttributeDataRanges is not null)
        {
            foreach (var type in EnumerateTypes(metadata))
            {
                var customAttributes = ReadMemoryPackUnionAttributes(metadata, type);
                if (customAttributes.Count == 0)
                    continue;

                targets.Add(new Dictionary<string, object?>
                {
                    ["full_name"] = CleanTypeName(type.FullName ?? BuildFullTypeName(type)),
                    ["custom_attributes"] = customAttributes,
                });
            }
        }

        var outputPath = Path.GetFullPath(unionOutputPath);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        var options = new JsonSerializerOptions { WriteIndented = true };
        File.WriteAllText(
            outputPath,
            JsonSerializer.Serialize(new { version = 0, targets }, options),
            new UTF8Encoding(false));
    }

    private static List<Dictionary<string, object?>> ReadMemoryPackUnionAttributes(
        Il2CppMetadata metadata,
        Il2CppTypeDefinition ownerType)
    {
        var blob = ReadCustomAttributeBlob(metadata, ownerType.Token);
        if (blob is null || blob.Length == 0)
            return [];

        var result = new List<Dictionary<string, object?>>();
        try
        {
            using var stream = new MemoryStream(blob);
            using var reader = new BinaryReader(stream, Encoding.UTF8, true);
            var attributeCount = ReadCompressedUInt(stream);
            var constructors = new Il2CppMethodDefinition[attributeCount];
            for (var index = 0; index < attributeCount; index++)
                constructors[index] = metadata.methodDefs[reader.ReadUInt32()];

            foreach (var constructor in constructors)
            {
                var constructorArgs = ReadCustomAttributeConstructorArgs(stream);
                var attributeType = constructor.DeclaringType?.FullName ?? "";
                if (
                    attributeType == "MemoryPack.MemoryPackUnionAttribute"
                    && TryBuildUnionAttribute(constructorArgs, out var attribute)
                )
                {
                    result.Add(attribute);
                }
            }
        }
        catch
        {
            return [];
        }

        return result;
    }

    private static byte[]? ReadCustomAttributeBlob(
        Il2CppMetadata metadata,
        uint token)
    {
        var ranges = metadata.AttributeDataRanges;
        if (ranges is null)
            return null;

        for (var index = 0; index < ranges.Count - 1; index++)
        {
            if (ranges[index].token != token)
                continue;

            var start = metadata.metadataHeader.attributeData.Offset + ranges[index].startOffset;
            var end = metadata.metadataHeader.attributeData.Offset + ranges[index + 1].startOffset;
            if (end <= start)
                return null;
            return metadata.ReadByteArrayAtRawAddress(start, (int)(end - start));
        }

        return null;
    }

    private static List<object?> ReadCustomAttributeConstructorArgs(Stream stream)
    {
        var ctorArgCount = ReadCompressedUInt(stream);
        var fieldCount = ReadCompressedUInt(stream);
        var propertyCount = ReadCompressedUInt(stream);
        var args = new List<object?>();
        using var reader = new BinaryReader(stream, Encoding.UTF8, true);

        for (var index = 0; index < ctorArgCount; index++)
            args.Add(ReadCustomAttributeValue(reader));

        for (var index = 0; index < fieldCount; index++)
        {
            _ = ReadCustomAttributeValue(reader);
            SkipCustomAttributeMemberIndex(stream);
        }

        for (var index = 0; index < propertyCount; index++)
        {
            _ = ReadCustomAttributeValue(reader);
            SkipCustomAttributeMemberIndex(stream);
        }

        return args;
    }

    private static bool TryBuildUnionAttribute(
        IReadOnlyList<object?> constructorArgs,
        out Dictionary<string, object?> attribute)
    {
        attribute = [];
        if (constructorArgs.Count < 2)
            return false;

        if (!TryConvertUnionTag(constructorArgs[0], out var tag))
            return false;

        if (constructorArgs[1] is not string unionType || string.IsNullOrWhiteSpace(unionType))
            return false;

        attribute = new Dictionary<string, object?>
        {
            ["attribute_type"] = "MemoryPack.MemoryPackUnionAttribute",
            ["rendered"] = $"MemoryPackUnion({tag}, typeof({unionType}))",
            ["tag"] = tag,
            ["union_type"] = unionType,
        };
        return true;
    }

    private static bool TryConvertUnionTag(object? value, out int tag)
    {
        switch (value)
        {
            case byte byteValue:
                tag = byteValue;
                return true;
            case sbyte signedByteValue:
                tag = signedByteValue;
                return true;
            case ushort ushortValue:
                tag = ushortValue;
                return true;
            case short shortValue:
                tag = shortValue;
                return true;
            case uint uintValue when uintValue <= int.MaxValue:
                tag = (int)uintValue;
                return true;
            case int intValue:
                tag = intValue;
                return true;
            default:
                tag = 0;
                return false;
        }
    }

    private static object? ReadCustomAttributeValue(BinaryReader reader)
    {
        var valueType = (Il2CppTypeEnum)reader.ReadByte();
        return valueType switch
        {
            Il2CppTypeEnum.IL2CPP_TYPE_BOOLEAN => reader.ReadBoolean(),
            Il2CppTypeEnum.IL2CPP_TYPE_CHAR => reader.ReadChar(),
            Il2CppTypeEnum.IL2CPP_TYPE_I1 => reader.ReadSByte(),
            Il2CppTypeEnum.IL2CPP_TYPE_U1 => reader.ReadByte(),
            Il2CppTypeEnum.IL2CPP_TYPE_I2 => reader.ReadInt16(),
            Il2CppTypeEnum.IL2CPP_TYPE_U2 => reader.ReadUInt16(),
            Il2CppTypeEnum.IL2CPP_TYPE_I4 => ReadCompressedInt(reader.BaseStream),
            Il2CppTypeEnum.IL2CPP_TYPE_U4 => (int)ReadCompressedUInt(reader.BaseStream),
            Il2CppTypeEnum.IL2CPP_TYPE_I8 => reader.ReadInt64(),
            Il2CppTypeEnum.IL2CPP_TYPE_U8 => reader.ReadUInt64(),
            Il2CppTypeEnum.IL2CPP_TYPE_R4 => reader.ReadSingle(),
            Il2CppTypeEnum.IL2CPP_TYPE_R8 => reader.ReadDouble(),
            Il2CppTypeEnum.IL2CPP_TYPE_STRING => ReadCustomAttributeString(reader),
            Il2CppTypeEnum.IL2CPP_TYPE_IL2CPP_TYPE_INDEX => ReadCustomAttributeTypeName(reader.BaseStream),
            Il2CppTypeEnum.IL2CPP_TYPE_ENUM => ReadCustomAttributeEnum(reader),
            _ => throw new InvalidDataException($"Unsupported custom attribute value type: {valueType}"),
        };
    }

    private static object ReadCustomAttributeEnum(BinaryReader reader)
    {
        var enumTypeIndex = ReadCompressedInt(reader.BaseStream);
        if (enumTypeIndex < 0 || LibCpp2IlMain.Binary is null)
            throw new InvalidDataException("Custom attribute enum type index is invalid.");

        var enumType = LibCpp2IlMain.Binary.GetType(
            Il2CppVariableWidthIndex<Il2CppType>.MakeTemporaryForFixedWidthUsage(enumTypeIndex));
        return ReadCustomAttributePrimitiveValue(
            reader,
            enumType.AsClass().EnumUnderlyingType.Type);
    }

    private static object ReadCustomAttributePrimitiveValue(
        BinaryReader reader,
        Il2CppTypeEnum valueType)
    {
        return valueType switch
        {
            Il2CppTypeEnum.IL2CPP_TYPE_BOOLEAN => reader.ReadBoolean(),
            Il2CppTypeEnum.IL2CPP_TYPE_CHAR => reader.ReadChar(),
            Il2CppTypeEnum.IL2CPP_TYPE_I1 => reader.ReadSByte(),
            Il2CppTypeEnum.IL2CPP_TYPE_U1 => reader.ReadByte(),
            Il2CppTypeEnum.IL2CPP_TYPE_I2 => reader.ReadInt16(),
            Il2CppTypeEnum.IL2CPP_TYPE_U2 => reader.ReadUInt16(),
            Il2CppTypeEnum.IL2CPP_TYPE_I4 => ReadCompressedInt(reader.BaseStream),
            Il2CppTypeEnum.IL2CPP_TYPE_U4 => ReadCompressedUInt(reader.BaseStream),
            Il2CppTypeEnum.IL2CPP_TYPE_I8 => reader.ReadInt64(),
            Il2CppTypeEnum.IL2CPP_TYPE_U8 => reader.ReadUInt64(),
            _ => throw new InvalidDataException(
                $"Unsupported custom attribute enum storage type: {valueType}"),
        };
    }

    private static string? ReadCustomAttributeString(BinaryReader reader)
    {
        var length = ReadCompressedInt(reader.BaseStream);
        if (length <= 0)
            return null;
        return Encoding.UTF8.GetString(reader.ReadBytes(length));
    }

    private static string ReadCustomAttributeTypeName(Stream stream)
    {
        var typeIndex = ReadCompressedInt(stream);
        if (typeIndex < 0 || LibCpp2IlMain.Binary is null)
            return "";
        var type = LibCpp2IlMain.Binary.GetType(
            Il2CppVariableWidthIndex<Il2CppType>.MakeTemporaryForFixedWidthUsage(typeIndex));
        return CleanTypeName(type.CoerceToUnderlyingTypeDefinition().FullName ?? "");
    }

    private static void SkipCustomAttributeMemberIndex(Stream stream)
    {
        var memberIndex = ReadCompressedInt(stream);
        if (memberIndex < 0)
            _ = ReadCompressedUInt(stream);
    }

    private static uint ReadCompressedUInt(Stream stream)
    {
        var first = stream.ReadByte();
        if (first < 0)
            throw new EndOfStreamException();

        var value = (byte)first;
        if (value < 128)
            return value;
        if (value == 240)
            return ReadUInt32LittleEndian(stream);
        if (value == byte.MaxValue)
            return uint.MaxValue;
        if (value == 254)
            return uint.MaxValue - 1;
        if ((value & 192) == 192)
        {
            return (value & ~192U) << 24
                | (uint)(ReadByte(stream) << 16)
                | (uint)(ReadByte(stream) << 8)
                | ReadByte(stream);
        }
        if ((value & 128) == 128)
            return (value & ~128U) << 8 | ReadByte(stream);

        throw new InvalidDataException($"Invalid compressed int first byte {value}.");
    }

    private static int ReadCompressedInt(Stream stream)
    {
        var unsigned = ReadCompressedUInt(stream);
        if (unsigned == uint.MaxValue)
            return int.MinValue;

        var isNegative = (unsigned & 1) == 1;
        unsigned >>= 1;
        if (isNegative)
            return -(int)(unsigned + 1);
        return (int)unsigned;
    }

    private static uint ReadUInt32LittleEndian(Stream stream)
    {
        return ReadByte(stream)
            | (uint)(ReadByte(stream) << 8)
            | (uint)(ReadByte(stream) << 16)
            | (uint)(ReadByte(stream) << 24);
    }

    private static byte ReadByte(Stream stream)
    {
        var value = stream.ReadByte();
        if (value < 0)
            throw new EndOfStreamException();
        return (byte)value;
    }

    private static IEnumerable<Il2CppTypeDefinition> EnumerateTypes(
        Il2CppMetadata metadata)
    {
        foreach (var image in metadata.imageDefinitions)
        {
            foreach (var type in image.Types ?? [])
            {
                foreach (var item in EnumerateTypeTree(type))
                    yield return item;
            }
        }
    }

    private static IEnumerable<Il2CppTypeDefinition> EnumerateTypeTree(
        Il2CppTypeDefinition type)
    {
        yield return type;
        foreach (var nestedType in type.NestedTypes ?? [])
        {
            foreach (var item in EnumerateTypeTree(nestedType))
                yield return item;
        }
    }

    private static string BuildFullTypeName(Il2CppTypeDefinition type)
    {
        var typeName = BuildTypeName(type);
        if (string.IsNullOrWhiteSpace(type.Namespace))
            return typeName;
        return $"{type.Namespace}.{typeName}";
    }

    private static string ExtractGenericArgument(string value, string genericTypeName)
    {
        var prefix = genericTypeName + "<";
        if (!value.StartsWith(prefix, StringComparison.Ordinal))
            return string.Empty;
        if (!value.EndsWith(">", StringComparison.Ordinal))
            return string.Empty;
        return value[prefix.Length..^1];
    }

    private static string BuildMethodName(Il2CppMethodDefinition method)
    {
        var methodName = SanitizeIdentifier(method.Name ?? "Method");
        var genericParameters = method.GenericContainer?.GenericParameters.Select(p => SanitizeIdentifier(p.Name ?? $"T{p.genericParameterIndexInOwner}")).ToArray() ?? [];
        if (genericParameters.Length == 0)
            return methodName;
        return $"{methodName}<{string.Join(", ", genericParameters)}>";
    }

    private static string BuildParameterList(Il2CppMethodDefinition method)
    {
        var parameters = method.Parameters ?? [];
        var rendered = parameters.Select(p =>
        {
            var modifier = p.Attributes.HasFlag(ParameterAttributes.Out) ? "out " :
                p.RawType?.Type == Il2CppTypeEnum.IL2CPP_TYPE_BYREF ? "ref " : string.Empty;
            return $"{modifier}{CleanTypeName(p.Type.ToString())} {SanitizeIdentifier(p.ParameterName ?? $"param{p.ParameterIndex}")}";
        });

        return "(" + string.Join(", ", rendered) + ")";
    }

    private static string BuildTypeName(Il2CppTypeDefinition type)
    {
        var name = SanitizeIdentifier(type.Name ?? "Type");
        var genericParameters = type.GenericContainer?.GenericParameters.Select(p => SanitizeIdentifier(p.Name ?? $"T{p.genericParameterIndexInOwner}")).ToArray() ?? [];
        if (genericParameters.Length == 0)
            return name;
        return $"{name}<{string.Join(", ", genericParameters)}>";
    }

    private static string BuildTypeAccess(Il2CppTypeDefinition type)
    {
        var visibility = type.Attributes & TypeAttributes.VisibilityMask;
        return visibility switch
        {
            TypeAttributes.Public or TypeAttributes.NestedPublic => "public",
            TypeAttributes.NestedFamily => "protected",
            TypeAttributes.NestedFamORAssem => "protected internal",
            TypeAttributes.NotPublic => "internal",
            _ => "private",
        };
    }

    private static string BuildFieldAccess(FieldAttributes attributes)
    {
        var access = attributes & FieldAttributes.FieldAccessMask;
        return access switch
        {
            FieldAttributes.Public => "public",
            FieldAttributes.Family => "protected",
            FieldAttributes.FamORAssem => "protected internal",
            FieldAttributes.Assembly => "internal",
            _ => "private",
        };
    }

    private static string BuildMethodAccess(MethodAttributes attributes)
    {
        var access = attributes & MethodAttributes.MemberAccessMask;
        return access switch
        {
            MethodAttributes.Public => "public",
            MethodAttributes.Family => "protected",
            MethodAttributes.FamORAssem => "protected internal",
            MethodAttributes.Assembly => "internal",
            _ => "private",
        };
    }

    private static string BuildPropertyAccess(Il2CppPropertyDefinition property)
    {
        var accessor = property.Getter ?? property.Setter;
        return accessor is null ? "public" : BuildMethodAccess(accessor.Attributes);
    }

    private static string CleanTypeName(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "void";
        return Regex.Replace(raw, @"`\d+", string.Empty).Replace('+', '.');
    }

    private static string SanitizeIdentifier(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "_";
        return Regex.Replace(raw, @"`\d+", string.Empty);
    }

    private static void RequireFile(string path)
    {
        if (!File.Exists(path))
            throw new FileNotFoundException("File not found: " + path);
    }

    private static Options? ParseArgs(string[] args)
    {
        string? binaryPath = null;
        string? metadataPath = null;
        string? outputPath = null;
        string? formatterOutputPath = null;
        string? unityVersion = null;
        var enableCnMetadataRecoveryShim = false;

        foreach (var arg in args)
        {
            if (arg.StartsWith("--binary-path=", StringComparison.OrdinalIgnoreCase))
                binaryPath = arg["--binary-path=".Length..].Trim('"');
            else if (arg.StartsWith("--metadata-path=", StringComparison.OrdinalIgnoreCase))
                metadataPath = arg["--metadata-path=".Length..].Trim('"');
            else if (arg.StartsWith("--output=", StringComparison.OrdinalIgnoreCase))
                outputPath = arg["--output=".Length..].Trim('"');
            else if (arg.StartsWith("--formatter-output=", StringComparison.OrdinalIgnoreCase))
                formatterOutputPath = arg["--formatter-output=".Length..].Trim('"');
            else if (arg.StartsWith("--unity-version=", StringComparison.OrdinalIgnoreCase))
                unityVersion = arg["--unity-version=".Length..].Trim('"');
            else if (arg.Equals("--enable-cn-metadata-recovery-shim", StringComparison.OrdinalIgnoreCase))
                enableCnMetadataRecoveryShim = true;
        }

        if (string.IsNullOrWhiteSpace(binaryPath) || string.IsNullOrWhiteSpace(metadataPath) || string.IsNullOrWhiteSpace(outputPath))
            return null;

        return new Options(
            binaryPath,
            metadataPath,
            outputPath,
            formatterOutputPath ?? string.Empty,
            unityVersion ?? string.Empty,
            enableCnMetadataRecoveryShim);
    }

    private static void PrintUsage()
    {
        Console.WriteLine("Usage:");
        Console.WriteLine("  dotnet run --project dumpcs_exporter -- --binary-path=<path> --metadata-path=<path> --unity-version=<version> --output=<path> [--formatter-output=<path>] [--enable-cn-metadata-recovery-shim]");
    }

    private sealed record Options(
        string BinaryPath,
        string MetadataPath,
        string OutputPath,
        string FormatterOutputPath,
        string UnityVersion,
        bool EnableCnMetadataRecoveryShim);
}
