using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using AssetRipper.Primitives;
using LibCpp2IL;
using LibCpp2IL.BinaryStructures;
using LibCpp2IL.Metadata;

internal static class Program
{
    private static int Main(string[] args)
    {
        try
        {
            var options = ParseArgs(args);
            if (options is null)
            {
                PrintUsage();
                return 1;
            }

            RequireFile(options.BinaryPath);
            RequireFile(options.MetadataPath);

            var unityVersion = string.IsNullOrWhiteSpace(options.UnityVersion)
                ? throw new InvalidOperationException("Missing unity version. Please pass --unity-version.")
                : UnityVersion.Parse(options.UnityVersion);

            if (!LibCpp2IlMain.LoadFromFile(options.BinaryPath, options.MetadataPath, unityVersion))
                throw new InvalidOperationException("Failed to load IL2CPP binary and metadata.");

            var metadata = LibCpp2IlMain.TheMetadata ?? throw new InvalidOperationException("Metadata not initialized.");
            var outputPath = Path.GetFullPath(options.OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

            using var writer = new StreamWriter(outputPath, false, new UTF8Encoding(false));
            WriteHeader(writer, options, unityVersion, metadata);

            for (var imageIndex = 0; imageIndex < metadata.imageDefinitions.Length; imageIndex++)
            {
                var image = metadata.imageDefinitions[imageIndex];
                var types = image.Types ?? [];

                writer.WriteLine();
                writer.WriteLine($"// Image {imageIndex}: {image.Name}");
                writer.WriteLine($"// Token: 0x{image.token:X8}");
                writer.WriteLine();

                foreach (var type in types.Where(t => t.DeclaringType is null))
                    WriteType(writer, type, 0);
            }

            Console.WriteLine($"dump.cs exported to {outputPath}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
            return 1;
        }
    }

    private static void WriteHeader(
        StreamWriter writer,
        Options options,
        UnityVersion unityVersion,
        Il2CppMetadata metadata)
    {
        writer.WriteLine("// dump.cs generated by ba-downloader dumpcs_exporter");
        writer.WriteLine($"// Binary: {options.BinaryPath}");
        writer.WriteLine($"// Metadata: {options.MetadataPath}");
        writer.WriteLine($"// UnityVersion: {unityVersion}");
        writer.WriteLine($"// MetadataVersion: {metadata.MetadataVersion}");
        writer.WriteLine($"// TypeDefinitions: {metadata.TypeDefinitionCount}");
        writer.WriteLine($"// MethodDefinitions: {metadata.MethodDefinitionCount}");
    }

    private static void WriteType(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var indentation = new string(' ', indent * 4);
        var namespaceName = string.IsNullOrEmpty(type.Namespace) ? "-" : type.Namespace;

        writer.WriteLine($"{indentation}// Namespace: {namespaceName}");
        writer.WriteLine($"{indentation}{BuildTypeDeclaration(type)} // TypeDefIndex: {type.TypeIndex.Value} Token: 0x{type.Token:X8}");
        writer.WriteLine($"{indentation}{{");

        WriteFields(writer, type, indent + 1);
        WriteProperties(writer, type, indent + 1);
        WriteMethods(writer, type, indent + 1);

        var nestedTypes = type.NestedTypes ?? [];
        if (nestedTypes.Length > 0)
        {
            writer.WriteLine();
            writer.WriteLine($"{new string(' ', (indent + 1) * 4)}// Nested Types");
            foreach (var nestedType in nestedTypes)
            {
                writer.WriteLine();
                WriteType(writer, nestedType, indent + 1);
            }
        }

        writer.WriteLine($"{indentation}}}");
        writer.WriteLine();
    }

    private static void WriteFields(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var fields = type.FieldInfos ?? [];
        if (fields.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine($"{indentation}// Fields");
        foreach (var field in fields)
        {
            var offset = field.FieldOffset >= 0 ? $"0x{field.FieldOffset:X}" : "static";
            writer.WriteLine(
                $"{indentation}{BuildFieldDeclaration(field.Field, field.Attributes)}; // {offset} Token: 0x{field.Field.token:X8}");
        }
    }

    private static void WriteProperties(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var properties = type.Properties ?? [];
        if (properties.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine();
        writer.WriteLine($"{indentation}// Properties");
        foreach (var property in properties)
        {
            var getter = property.Getter is not null ? "get; " : string.Empty;
            var setter = property.Setter is not null ? "set; " : string.Empty;
            var propertyType = CleanTypeName(property.PropertyType?.ToString() ?? "void");
            writer.WriteLine(
                $"{indentation}{BuildPropertyAccess(property)} {propertyType} {SanitizeIdentifier(property.Name ?? "property")} {{ {getter}{setter}}} // Token: 0x{property.token:X8}");
        }
    }

    private static void WriteMethods(StreamWriter writer, Il2CppTypeDefinition type, int indent)
    {
        var methods = type.Methods ?? [];
        if (methods.Length == 0)
            return;

        var indentation = new string(' ', indent * 4);
        writer.WriteLine();
        writer.WriteLine($"{indentation}// Methods");
        foreach (var method in methods)
        {
            writer.WriteLine(
                $"{indentation}// RVA: 0x{method.Rva:X} Offset: 0x{method.MethodOffsetInFile:X} VA: 0x{method.MethodPointer:X} Slot: {method.slot} Token: 0x{method.token:X8}");
            writer.WriteLine($"{indentation}{BuildMethodDeclaration(method)} {{ }}");
        }
    }

    private static string BuildTypeDeclaration(Il2CppTypeDefinition type)
    {
        var parts = new List<string> { BuildTypeAccess(type) };
        if (type.IsInterface)
        {
            parts.Add("interface");
        }
        else if (type.IsEnumType)
        {
            parts.Add("enum");
        }
        else if (type.IsValueType)
        {
            parts.Add("struct");
        }
        else
        {
            if (type.Attributes.HasFlag(TypeAttributes.Abstract) && type.Attributes.HasFlag(TypeAttributes.Sealed))
                parts.Add("static");
            else
            {
                if (type.Attributes.HasFlag(TypeAttributes.Abstract))
                    parts.Add("abstract");
                if (type.Attributes.HasFlag(TypeAttributes.Sealed))
                    parts.Add("sealed");
            }

            parts.Add("class");
        }

        parts.Add(BuildTypeName(type));

        var inheritance = new List<string>();
        if (!type.IsInterface && !type.IsEnumType && !type.IsValueType)
        {
            var baseTypeName = CleanTypeName(type.BaseType?.ToString() ?? string.Empty);
            if (!string.IsNullOrEmpty(baseTypeName) && baseTypeName != "System.Object" && baseTypeName != "void")
                inheritance.Add(baseTypeName);
        }

        var interfaces = type.Interfaces ?? [];
        inheritance.AddRange(interfaces.Select(i => CleanTypeName(i.ToString())));
        if (inheritance.Count > 0)
            parts.Add(": " + string.Join(", ", inheritance.Distinct()));

        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildFieldDeclaration(Il2CppFieldDefinition field, FieldAttributes attributes)
    {
        var parts = new List<string> { BuildFieldAccess(attributes) };
        if (attributes.HasFlag(FieldAttributes.Static))
            parts.Add("static");
        if (attributes.HasFlag(FieldAttributes.InitOnly))
            parts.Add("readonly");
        if (attributes.HasFlag(FieldAttributes.Literal))
            parts.Add("const");
        parts.Add(CleanTypeName(field.FieldType?.ToString() ?? "void"));
        parts.Add(SanitizeIdentifier(field.Name ?? "field"));
        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildMethodDeclaration(Il2CppMethodDefinition method)
    {
        var parts = new List<string> { BuildMethodAccess(method.Attributes) };
        if (method.IsStatic)
            parts.Add("static");
        if (method.Attributes.HasFlag(MethodAttributes.Abstract))
            parts.Add("abstract");
        else if (method.Attributes.HasFlag(MethodAttributes.Virtual))
            parts.Add("virtual");

        parts.Add(CleanTypeName(method.ReturnType?.ToString() ?? "void"));
        parts.Add(BuildMethodName(method) + BuildParameterList(method));
        return string.Join(" ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    private static string BuildMethodName(Il2CppMethodDefinition method)
    {
        var methodName = SanitizeIdentifier(method.Name ?? "Method");
        var genericParameters = method.GenericContainer?.GenericParameters.Select(p => SanitizeIdentifier(p.Name ?? $"T{p.genericParameterIndexInOwner}")).ToArray() ?? [];
        if (genericParameters.Length == 0)
            return methodName;
        return $"{methodName}<{string.Join(", ", genericParameters)}>";
    }

    private static string BuildParameterList(Il2CppMethodDefinition method)
    {
        var parameters = method.Parameters ?? [];
        var rendered = parameters.Select(p =>
        {
            var modifier = p.Attributes.HasFlag(ParameterAttributes.Out) ? "out " :
                p.RawType?.Type == Il2CppTypeEnum.IL2CPP_TYPE_BYREF ? "ref " : string.Empty;
            return $"{modifier}{CleanTypeName(p.Type.ToString())} {SanitizeIdentifier(p.ParameterName ?? $"param{p.ParameterIndex}")}";
        });

        return "(" + string.Join(", ", rendered) + ")";
    }

    private static string BuildTypeName(Il2CppTypeDefinition type)
    {
        var name = SanitizeIdentifier(type.Name ?? "Type");
        var genericParameters = type.GenericContainer?.GenericParameters.Select(p => SanitizeIdentifier(p.Name ?? $"T{p.genericParameterIndexInOwner}")).ToArray() ?? [];
        if (genericParameters.Length == 0)
            return name;
        return $"{name}<{string.Join(", ", genericParameters)}>";
    }

    private static string BuildTypeAccess(Il2CppTypeDefinition type)
    {
        var visibility = type.Attributes & TypeAttributes.VisibilityMask;
        return visibility switch
        {
            TypeAttributes.Public or TypeAttributes.NestedPublic => "public",
            TypeAttributes.NestedFamily => "protected",
            TypeAttributes.NestedFamORAssem => "protected internal",
            TypeAttributes.NotPublic => "internal",
            _ => "private",
        };
    }

    private static string BuildFieldAccess(FieldAttributes attributes)
    {
        var access = attributes & FieldAttributes.FieldAccessMask;
        return access switch
        {
            FieldAttributes.Public => "public",
            FieldAttributes.Family => "protected",
            FieldAttributes.FamORAssem => "protected internal",
            FieldAttributes.Assembly => "internal",
            _ => "private",
        };
    }

    private static string BuildMethodAccess(MethodAttributes attributes)
    {
        var access = attributes & MethodAttributes.MemberAccessMask;
        return access switch
        {
            MethodAttributes.Public => "public",
            MethodAttributes.Family => "protected",
            MethodAttributes.FamORAssem => "protected internal",
            MethodAttributes.Assembly => "internal",
            _ => "private",
        };
    }

    private static string BuildPropertyAccess(Il2CppPropertyDefinition property)
    {
        var accessor = property.Getter ?? property.Setter;
        return accessor is null ? "public" : BuildMethodAccess(accessor.Attributes);
    }

    private static string CleanTypeName(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "void";
        return Regex.Replace(raw, @"`\\d+", string.Empty).Replace('+', '.');
    }

    private static string SanitizeIdentifier(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "_";
        return Regex.Replace(raw, @"`\\d+", string.Empty);
    }

    private static void RequireFile(string path)
    {
        if (!File.Exists(path))
            throw new FileNotFoundException("File not found: " + path);
    }

    private static Options? ParseArgs(string[] args)
    {
        string? binaryPath = null;
        string? metadataPath = null;
        string? outputPath = null;
        string? unityVersion = null;

        foreach (var arg in args)
        {
            if (arg.StartsWith("--binary-path=", StringComparison.OrdinalIgnoreCase))
                binaryPath = arg["--binary-path=".Length..].Trim('"');
            else if (arg.StartsWith("--metadata-path=", StringComparison.OrdinalIgnoreCase))
                metadataPath = arg["--metadata-path=".Length..].Trim('"');
            else if (arg.StartsWith("--output=", StringComparison.OrdinalIgnoreCase))
                outputPath = arg["--output=".Length..].Trim('"');
            else if (arg.StartsWith("--unity-version=", StringComparison.OrdinalIgnoreCase))
                unityVersion = arg["--unity-version=".Length..].Trim('"');
        }

        if (string.IsNullOrWhiteSpace(binaryPath) || string.IsNullOrWhiteSpace(metadataPath) || string.IsNullOrWhiteSpace(outputPath))
            return null;

        return new Options(binaryPath, metadataPath, outputPath, unityVersion ?? string.Empty);
    }

    private static void PrintUsage()
    {
        Console.WriteLine("Usage:");
        Console.WriteLine("  dotnet run --project dumpcs_exporter -- --binary-path=<path> --metadata-path=<path> --unity-version=<version> --output=<path>");
    }

    private sealed record Options(
        string BinaryPath,
        string MetadataPath,
        string OutputPath,
        string UnityVersion);
}
